GET http://localhost:3000
###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"wilmer Correa",
    "email":"wilmertellote@gmail.com",
    "password":"wilmer"
    
}
####
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"wilmertellote@gmail.com",
    "password":"wilmertambien"
    
}